n = int(input('Digite um numero: '))
print('O dobro de n é:', n**2 )
print('O triplo de n é: ', n ** 3 )
print('A raiz quadrada de n é:', n ** (1/2 ))
print('A raiz quadrada de n é {:.3f}' .format(n ** (1/2)))